domain: "home-server.dev"
akeyless:
  enabled: false
  path: "/kind-homelab"
cloudflare:
  email: "Jonas@Hess.pm"
letsencrypt:
  email: "Jonas@Hess.pm"
homeassistant:
  enabled: false
  volumes:
    config: "/mnt/tank1/unencrypted/apps/homeassistant/config"
traefik:
  enabled: false
  additionalExposedPorts:
    sftpgo:
      port: 2022
      protocol: TCP
#     plex:
#       port: 32400
#       protocol: TCP
#     samba-548:
#       port: 548
#       protocol: TCP
#     samba-139:
#       port: 139
#       protocol: TCP
#     samba-445:
#       port: 445
#       protocol: TCP

  volumes:
    data: "/mnt/tank1/unencrypted/apps/traefik/data"
  loadBalancerIP: "192.168.0.80"
traefik_forward_auth:
# https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_t9DQfKlSX/.well-known/openid-configuration
  oidc_issuer_url: "https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_t9DQfKlSX/.well-known/jwks.json"
  oidc_client_id: "6e1bl5i55ao7bhhcufk85ussm"
sftpgo:
  enabled: false
  volumes:
    data: "/mnt/tank1/unencrypted/apps/sftpgo/data"
    home: "/mnt/tank1/encrypted/apps/sftpgo/home"
apps:
  test:
    enabled: false
    generic:
      persistentVolumeClaims:
      - name: "data"
        hostPath: "/mnt/tank1/unencrypted/apps/test/data"
  sftpgo:
    enabled: true
    generic:
      persistentVolumeClaims:
      - name: "data"
        hostPath: "/mnt/tank1/unencrypted/apps/sftpgo/data"
      - name: "home"
        hostPath: "/mnt/tank1/encrypted/apps/sftpgo/home"
