domain: "home-server.dev"
akeyless:
  path: "/kind-homelab"
cloudflare:
  email: "Jonas@Hess.pm"
letsencrypt:
  email: "Jonas@Hess.pm"
nginx:
  enabled: true
  message: "Hello from nginx!"
  replicaCount: 3
homeassistant:
  volumes:
    config: "/mnt/tank1/unencrypted/apps/homeassistant/config"
traefik-forward-auth:
# https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_t9DQfKlSX/.well-known/openid-configuration
  oidc-issuer-url: "https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_t9DQfKlSX"
  oidc-client-id: "6e1bl5i55ao7bhhcufk85ussm"