domain: "home-server.dev"
cloudflare:
  email: "Jonas@Hess.pm"
letsencrypt:
  email: "Jonas@Hess.pm"
traefik_forward_auth:
# https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_t9DQfKlSX/.well-known/openid-configuration
  oidc_issuer_url: "https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_t9DQfKlSX/.well-known/jwks.json"
  oidc_client_id: "6e1bl5i55ao7bhhcufk85ussm"
sftpgo:
  enabled: false
  volumes:
    data: "/mnt/tank1/unencrypted/apps/sftpgo/data"
    home: "/mnt/tank1/encrypted/apps/sftpgo/home"
apps:
  test:
    enabled: false
#     generic:
      #       persistentVolumeClaims:
      #       - name: "data"
      #         hostPath: "/mnt/tank1/unencrypted/apps/sftpgo/data"
      #       - name: "home"
      #         hostPath: "/mnt/tank1/encrypted/apps/sftpgo/home"
  akeyless:
    enabled: false
    path: "/kind-homelab"
  traefik:
    enabled: false
    additionalExposedPorts:
      sftpgo:
        port: 2022
        protocol: TCP
    #     plex:
    #       port: 32400
    #       protocol: TCP
    #     samba-548:
    #       port: 548
    #       protocol: TCP
    #     samba-139:
    #       port: 139
    #       protocol: TCP
    #     samba-445:
    #       port: 445
    #       protocol: TCP
    loadBalancerIP: "192.168.0.80"
    generic:
      persistentVolumeClaims:
      - name: "data"
        hostPath: "/mnt/tank1/unencrypted/apps/traefik/data"
  homeassistant:
    enabled: false
    generic:
      deployment:
        image: "lscr.io/linuxserver/homeassistant:latest"
        ports:
          - containerPort: 8123
        pvcMounts:
          config:
            mountPath: "/config"
            hostPath: "/mnt/tank1/unencrypted/apps/homeassistant/config"
      service:
        ports:
          - name: http
            port: 8123
      ingress:
        https:
          - subdomain: "homeassistant"
            port: 8123
            middlewares:
              - name: "traefik-forward-auth"
                namespace: "argocd"
  sftpgo:
    enabled: false
    generic:
      deployment:
        image: "drakkan/sftpgo:latest"
        ports:
          - containerPort: 8080
          - containerPort: 2022
        pvcMounts:
          data:
            mountPath: "/srv/sftpgo"
            hostPath: "/mnt/tank1/unencrypted/apps/sftpgo/data"
          home:
            mountPath: "/var/lib/sftpgo"
            hostPath: "/mnt/tank1/encrypted/apps/sftpgo/home"
      service:
        ports:
          - name: http
            port: 8080
          - name: sftp
            port: 2022
            protocol: TCP
      ingress:
        https:
          - subdomain: "sftpgo"
            port: 8080
            middlewares:
              - name: "traefik-forward-auth"
                namespace: "argocd"
        tcp:
          - port: 2022
