domain: "home-server.dev"
akeyless:
  path: "/kind-homelab"
cloudflare:
  email: "Jonas@Hess.pm"
letsencrypt:
  email: "Jonas@Hess.pm"
nginx:
  enabled: true
  message: "Hello from nginx!"
  replicaCount: 3
homeassistant:
  volumes:
    config: "/mnt/tank1/unencrypted/apps/homeassistant/config"