apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: traefik-forward-auth-es
  namespace: argocd
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: SecretStore
    name: akeyless-secret-store

  target:
    name: traefik-forward-auth
    creationPolicy: Owner

  data:
    - secretKey: "PROVIDERS_OIDC_CLIENT_SECRET"
      remoteRef:
        key: "{{.Values.akeyless.path}}/oidc/traefik-forward-auth/client_secret"
    - secretKey: "SECRET"
      remoteRef:
        key: "{{.Values.akeyless.path}}/oidc/traefik-forward-auth/secret"