---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-forward-auth
  namespace: argocd
data:
  INSECURE_COOKIE: 'true'
  COOKIE_DOMAIN: {{ .Values.domain }}
  DOMAINS: {{ .Values.domain }}
  AUTH_HOST: auth.{{ .Values.domain }}
  URL_PATH: /_oauth
  DEFAULT_PROVIDER: oidc
  PROVIDERS_OIDC_ISSUER_URL: "https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_A6gtz8gw5/.well-known/jwks.json"
  PROVIDERS_OIDC_CLIENT_ID: "5vmqlfbdhdrma83s40bnrbb59i"
