{{- if .Values.apps.traefik.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cloudflare
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

spec:
  plugin:
    traefik-plugin-cloudflare:
      overwriteRequestHeader: true
      trustedCIDRs: []
      debug: true
{{- end -}}