{{- if .Values.apps.traefik.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-traefik-data
  namespace: argocd
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
{{- end -}}