apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-pv
  namespace: argocd
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    type: Directory
    path: {{ .Values.traefik.volumes.data }}
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-traefik-data
    namespace: argocd