{{- range $appName, $app := .Values.apps }}
  {{- if $app.enabled }}
    {{- if and $app.generic $app.generic.deployment }}
      {{- $deployment := $app.generic.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}-deployment
  namespace: argocd
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
    spec:
      containers:
        - name: {{ $appName }}
          image: {{ $deployment.image }}
          ports:
            {{- range $port := $deployment.ports }}
            - containerPort: {{ $port.containerPort }}
            {{- end }}
          volumeMounts:
            {{- range $mountName, $mount := $deployment.pvcMounts }}
            - mountPath: "{{ $mount.mountPath }}"
              name: {{ $appName }}-{{ $mountName }}-volume
            {{- end }}
      volumes:
        {{- range $mountName, $mount := $deployment.pvcMounts }}
        - name: {{ $appName }}-{{ $mountName }}-volume
          persistentVolumeClaim:
            claimName: {{ $appName }}-{{ $mountName }}-pvc
        {{- end }}
{{- range $mountName, $mount := $deployment.pvcMounts }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{$appName}}-{{ $mountName }}-pv"
  namespace: argocd
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    type: Directory
    path: {{ $mount.hostPath }}
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: "{{$appName}}-{{ $mountName }}-pvc"
    namespace: argocd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{$appName}}-{{ $mountName }}-pvc"
  namespace: argocd
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
{{- end }}




    {{- end }}
  {{- end }}
{{- end }}