{{- range $appName, $app := .Values.apps }}
  {{- if $app.enabled }}
    {{- if and $app.generic $app.generic.ingress }}
       {{- if $app.generic.ingress.https }}
         {{- range $ingress := $app.generic.ingress.https }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $appName }}-https-{{ $ingress.port }}
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ $ingress.subdomain }}.{{ $.Values.domain}}`)
      kind: Rule
      priority: 10
      services:
        - name: {{ $appName }}-service
          port: {{ $ingress.port }}
      {{- if $ingress.middlewares }}
      middlewares:
        {{- range $middleware := $ingress.middlewares }}
        - name: {{ $middleware.name }}
          namespace: {{ $middleware.namespace }}
        {{- end }}
      {{- end }}
  tls:
    certResolver: cloudflare
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}