{{- range $appName, $app := .Values.apps }}
  {{- if $app.enabled }}
    {{- if and $app.generic $app.generic.ingress $app.generic.ingress.tcp }}
      {{- range $ingress := $app.generic.ingress.tcp }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $appName }}-tcp-{{ $ingress.port }}
  namespace: argocd
spec:
  entryPoints:
    - {{ $appName }}
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ $appName }}-service
          port: {{ $ingress.port }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}