{{- range $appName, $app := .Values.apps }}
  {{- if $app.enabled }}
    {{- range $pvc := $app.generic.persistentVolumeClaims }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{$appName}}-{{ $pvc.name }}-pv"
  namespace: argocd
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    type: Directory
    path: {{ $pvc.hostPath }}
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: "{{$appName}}-{{ $pvc.name }}-pvc"
    namespace: argocd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{$appName}}-{{ $pvc.name }}-pvc"
  namespace: argocd
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
    {{- end }}
  {{- end }}
{{- end }}