apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant-deployment
  namespace: argocd
  labels:
    app: containous
    name: homeassistant-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - name: homeassistant
          image: lscr.io/linuxserver/homeassistant:latest
          ports:
            - containerPort: 8123
          volumeMounts:
            - mountPath: "/config"
              name: homeassistant-config
      volumes:
        - name: homeassistant-config
          persistentVolumeClaim:
            claimName: homeassistant-config-pvc
