apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-config-pv
  namespace: argocd
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    type: Directory
    path: {{.Values.homeassistant.volumes.config}}
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: homeassistant-config-pvc
    namespace: argocd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config-pvc
  namespace: argocd
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi