{{- if .Values.homeassistant.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant-https
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homeassistant.{{ .Values.domain}}`)
      kind: Rule
      priority: 10
      services:
        - name: homeassistant-service
          port: 8123
      middlewares:
        - name: traefik-forward-auth
          namespace: argocd
  tls:
    certResolver: cloudflare
{{- end -}}