{{- if .Values.homeassistant.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-service
  namespace: argocd
spec:
  ports:
    - name: http
      port: 8123
  selector:
    app: homeassistant
{{- end -}}