{{- if .Values.apps.aws.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecr-registry-helper-external-secret
  namespace: argocd
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: SecretStore
    name: akeyless-secret-store

  target:
    name: ecr-registry-helper-secrets
    creationPolicy: Owner

  data:
    - secretKey: "AWS_SECRET_ACCESS_KEY"
      remoteRef:
        key: "{{.Values.apps.akeyless.path}}/aws/ecr/AWS_SECRET_ACCESS_KEY"
    - secretKey: "AWS_ACCESS_KEY_ID"
      remoteRef:
        key: "{{.Values.apps.akeyless.path}}/aws/ecr/AWS_ACCESS_KEY_ID"
    - secretKey: "AWS_ACCOUNT"
      remoteRef:
        key: "{{.Values.apps.akeyless.path}}/aws/ecr/AWS_ACCOUNT"

{{- end -}}