apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftpgo-deployment
  namespace: argocd
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sftpgo
  template:
    metadata:
      labels:
        app: sftpgo
    spec:
      containers:
        - name: sftpgo
          image: drakkan/sftpgo:latest
          ports:
            - containerPort: 8080
            - containerPort: 2022
          volumeMounts:
            - mountPath: "/srv/sftpgo"
              name: sftpgo-data-volume
            - mountPath: "/var/lib/sftpgo"
              name: sftpgo-home-volume
      volumes:
        - name: sftpgo-data-volume
          persistentVolumeClaim:
            claimName: sftpgo-data-pvc
        - name: sftpgo-home-volume
          persistentVolumeClaim:
            claimName: sftpgo-home-pvc