apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: sftp-route-tcp
  namespace: argocd
spec:
  entryPoints:
    - sftp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: sftpgo-service
          port: 2022
          proxyProtocol:
            version: 2