apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sftpgo-https
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sftpgo.{{ .Values.domain}}`)
      kind: Rule
      priority: 10
      services:
        - name: sftpgo-service
          port: 8080
      middlewares:
        - name: traefik-forward-auth
          namespace: argocd
  tls:
    certResolver: cloudflare