{{- if .Values.apps.sftpgo.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: sftpgo-service
  namespace: argocd
spec:
  ports:
    - name: http
      port: 8080
    - name: sftp
      port: 2022
      protocol: TCP
  selector:
    app: sftpgo
{{- end -}}