{{- if .Values.apps.sftpgo.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: sftpgo-config
  namespace: argocd
data:
  sftpgo.json: |
    {
      "httpd": {
        "enabled_login_methods": ["password", "public_key", "oidc"],
        "oidc": {
          "config_url": {{ .Values.traefik_forward_auth.oidc_issuer_url | quote }},
          "client_id": {{ .Values.traefik_forward_auth.oidc_client_id | quote }},
          "redirect_base_url": "https://sftpgo.{{ .Values.domain}}",
          "username_field": "name",
          "role_field": "custom:sftpgo_role"
        }
      }
    }
{{- end -}}