{{- if .Values.apps.sftpgo.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: sftpgo-config-map
  namespace: argocd
data:
  SFTPGO_HTTPD__BINDINGS__ENABLED_LOGIN_METHODS: "0"
  SFTPGO_HTTPD__BINDINGS__0__OIDC__CONFIG_URL: {{ .Values.traefik_forward_auth.oidc_issuer_url | quote }}
  SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_ID: {{ .Values.traefik_forward_auth.oidc_client_id | quote }}
{{/*  SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_SECRET: {{ .Values.traefik_forward_auth.oidc_client_secret | quote }}*/}}
  SFTPGO_HTTPD__BINDINGS__0__OIDC__REDIRECT_BASE_URL: "https://sftpgo.{{ .Values.domain}}"
  SFTPGO_HTTPD__BINDINGS__0__OIDC__USERNAME_FIELD: "email"
{{/*  SFTPGO_HTTPD__BINDINGS__0__OIDC__ROLE_FIELD: "sftpgo"*/}}

{{- end -}}