{{- if .Values.sftpgo.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sftpgo-data-pv
  namespace: argocd
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    type: Directory
    path: {{.Values.sftpgo.volumes.data}}
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: sftpgo-data-pvc
    namespace: argocd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftpgo-data-pvc
  namespace: argocd
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
{{- end -}}