{{- if .Values.apps.argocd.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-external-secret
  namespace: argocd
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: SecretStore
    name: akeyless-secret-store

  target:
    name: argocd-secret
    creationPolicy: Owner
    labels:
      app.kubernetes.io/name: argocd-secret
      app.kubernetes.io/part-of: argocd

  data:
    - secretKey: "oidc.auth0.clientSecret"
      remoteRef:
        key: "{{.Values.apps.akeyless.path}}/oidc/traefik-forward-auth/client_secret"
{{- end -}}